[package]
name = "matchsorter"
version = "0.1.0"
edition = "2024"

[dependencies]
unicode-normalization = "0.1"
memchr = "2.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmarks"
harness = false
